"""Historical A0/A1 test compatibility imports; not a production API.
"""

from exqserve.tool_wire.compiler import ToolWireCompileError, compile_tool_wire_plan
from exqserve.tool_wire.contracts import (
    ActivationRequirement,
    ActivationTriggerSpec,
    ArgumentBranchPlan,
    ArgumentFramingSelector,
    ArgumentFramingSelectorRule,
    ArgumentFramingVariant,
    ArgumentOccurrenceCapabilities,
    ArgumentOrderingMode,
    ArgumentOrderPlan,
    CloseLanguage,
    CompileBudget,
    CompileBudgetResult,
    CompiledToolWirePlan,
    ConstraintCompilerCapabilities,
    ConstraintValueMode,
    LiteralTerminal,
    NameCodec,
    NamedTerminal,
    NonEmptinessStatus,
    PlanCompileDisposition,
    RepresentabilityStatus,
    SchemaSemanticAuthority,
    ToolBranchPlan,
    ToolMultiplicity,
    ToolWireSpec,
    ValueCodecKind,
    ValueFraming,
    ValueFramingKind,
    WireArgumentOccurrence,
    WireChannel,
    WireToolCall,
    WireToolSequence,
    encode_lossless_raw_string,
)
from exqserve.tool_wire.engine import (
    DeterministicToolWireEngine,
    ToolWireEngineIssue,
    ToolWireEngineResult,
    ToolWireEngineStatus,
)
from exqserve.tool_wire.lark_constraint import (
    ToolWireConstraintCompileError,
    constraint_grammar_fingerprint,
)
from tests.tool_wire._legacy_admission import (
    PlanAdmissionIssue,
    PlanAdmissionResult,
    admit_tool_sequence,
    admit_validation_only_tool_sequence,
)
from tests.tool_wire._legacy_certification import (
    CertificationIssue,
    CertificationResult,
    PromptArgumentWireObservation,
    PromptWireObservation,
    certify_prompt_template_parity,
)
from tests.tool_wire._legacy_shadow import ToolWireShadowResult, certify_engine_shadow

__all__ = [
    "ActivationRequirement",
    "ActivationTriggerSpec",
    "ArgumentBranchPlan",
    "ArgumentFramingSelector",
    "ArgumentFramingSelectorRule",
    "ArgumentFramingVariant",
    "ArgumentOccurrenceCapabilities",
    "ArgumentOrderPlan",
    "ArgumentOrderingMode",
    "CertificationIssue",
    "CertificationResult",
    "CloseLanguage",
    "CompileBudget",
    "CompileBudgetResult",
    "CompiledToolWirePlan",
    "ConstraintCompilerCapabilities",
    "ConstraintValueMode",
    "DeterministicToolWireEngine",
    "LiteralTerminal",
    "NameCodec",
    "NamedTerminal",
    "NonEmptinessStatus",
    "PlanAdmissionIssue",
    "PlanAdmissionResult",
    "PlanCompileDisposition",
    "PromptArgumentWireObservation",
    "PromptWireObservation",
    "RepresentabilityStatus",
    "SchemaSemanticAuthority",
    "ToolBranchPlan",
    "ToolMultiplicity",
    "ToolWireCompileError",
    "ToolWireConstraintCompileError",
    "ToolWireEngineIssue",
    "ToolWireEngineResult",
    "ToolWireEngineStatus",
    "ToolWireShadowResult",
    "ToolWireSpec",
    "ValueCodecKind",
    "ValueFraming",
    "ValueFramingKind",
    "WireArgumentOccurrence",
    "WireChannel",
    "WireToolCall",
    "WireToolSequence",
    "admit_tool_sequence",
    "admit_validation_only_tool_sequence",
    "certify_engine_shadow",
    "certify_prompt_template_parity",
    "compile_tool_wire_plan",
    "constraint_grammar_fingerprint",
    "encode_lossless_raw_string",
]
